# Generated by Django 5.2.9 on 2025-12-09 23:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Genero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Gênero')),
            ],
            options={
                'verbose_name': 'Gênero',
                'verbose_name_plural': 'Gêneros',
            },
        ),
        migrations.CreateModel(
            name='Plataforma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Plataforma de streaming')),
                ('site', models.CharField(blank=True, max_length=150, verbose_name='Site da plataforma')),
            ],
            options={
                'verbose_name': 'Plataforma',
                'verbose_name_plural': 'Plataformas',
            },
        ),
        migrations.CreateModel(
            name='Obra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=150, verbose_name='Título')),
                ('tipo', models.CharField(choices=[('FILME', 'Filme'), ('SERIE', 'Série')], max_length=10, verbose_name='Tipo')),
                ('status', models.CharField(choices=[('ASSISTIDO', 'Assistido'), ('VER', 'Quero ver')], max_length=10, verbose_name='Status')),
                ('nota', models.IntegerField(blank=True, null=True, verbose_name='Nota (0–10)')),
                ('comentario', models.TextField(blank=True, verbose_name='Comentário')),
                ('data_registro', models.DateField(auto_now_add=True, verbose_name='Data de registro')),
                ('data_atualizacao', models.DateField(auto_now=True, verbose_name='Última atualização')),
                ('genero', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.genero', verbose_name='Gênero')),
                ('plataforma', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.plataforma', verbose_name='Plataforma')),
            ],
            options={
                'verbose_name': 'Obra',
                'verbose_name_plural': 'Obras',
                'ordering': ['titulo'],
            },
        ),
    ]
